# Generated by Django 4.2.9 on 2024-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(default="lenovo", max_length=30)),
                ("size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rno", models.IntegerField()),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(max_length=10)),
                ("cropname", models.CharField(max_length=30)),
            ],
        ),
    ]
