# Generated by Django 4.2.9 on 2024-04-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_img", models.ImageField(upload_to="")),
                ("item_title", models.CharField(max_length=50)),
                ("item_detail", models.TextField()),
                ("item_date", models.DateField()),
                ("item_quant", models.IntegerField(default=0)),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
