# Generated by Django 4.2.9 on 2024-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="item_img",
            field=models.ImageField(upload_to="sell/"),
        ),
    ]
