# Generated by Django 4.2.9 on 2024-04-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0002_alter_sell_item_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="sell",
            name="user_name",
            field=models.CharField(default="lenovo", max_length=30),
        ),
    ]
