# Generated by Django 4.2.9 on 2024-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0003_sell_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell", name="item_img", field=models.ImageField(upload_to=""),
        ),
    ]
